{{- if .Values.apiserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge-logs.apiserver.serviceName" . }}
  namespace: {{ include "edge-logs.namespace" . }}
  labels:
    {{- include "edge-logs.labels" . | nindent 4 }}
    app.kubernetes.io/component: apiserver
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
    - name: http
      port: {{ .Values.apiserver.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "edge-logs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: apiserver
{{- end }}
